### ISSUE TITLE
Interpolation issue when using additional_resource_groups

### ISSUE THREAD

**Issue by mgmuk** [castai/terraform-castai-aks#74]
https://github.com/castai/terraform-castai-aks/blob/e97ad51f73eed3b5d1e18e4bfa65411a8970d053/iam.tf#L79C3-L79C101

Provider version: 7.8.0
Module version: 5.3.0
Terraform version: 1.8.5
Error: `Error: Invalid template interpolation value
│ 
│   on .terraform/modules/castai-aks-cluster/iam.tf line 79, in resource "azurerm_role_assignment" "castai_additional_resource_groups":
│   79:   description        = "castai role assignment for resource group ${var.additional_resource_groups}"
│     ├────────────────
│     │ var.additional_resource_groups is list of string with 1 element
│ 
│ Cannot include the given value in a string template: string required.
`

Description: When the value of `var.additional_resource_groups` is provided as a list of string the description in this resource fails terraform validation as it expects a string. 

A suitable change could be:
`description        = "castai role assignment for resource group ${each.key}"`

**Comment by aldor007** [comment]
Thank you @mgmuk  for providing a fix.
